Support splat expansions inside tuple and array literals
crystal-lang/crystal pull request #10429
Opened 2021-02-20 15:06 UTC by HertzDevil

Implements #3718. Does not implement double splats, https://github.com/crystal-lang/crystal/issues/3718#issuecomment-782248824 (`#to_array_splat`), and https://github.com/crystal-lang/crystal/issues/3718#issuecomment-782579396 (`__crystal_first`). The codegen portion for `Tuple` splats is copied directly from #10193's [head](https://github.com/crystal-lang/crystal/pull/10193/commits/9ed19b90976e03a25728a8bc7dc3d4bd871791f4).

The different expansions have their own requirements on the splatted value's interface:

```crystal
{*exp}      # `exp` must be a `Tuple` instance, it cannot be a union of `Tuple`s (of different arities)
[*exp]      # `exp` must be an `Enumerable` instance
[*exp] of T # `exp` must be an `Enumerable(U)` instance for some `U` <= `T`
T{*exp}     # `exp` must respond to `#each(& : _ -> _)`
            # if additionally `T` is an uninstantiated generic type, `exp` must also respond to `#first`
```

Very few array-like types implement `#each` but do not include `Enumerable`, so the requirement on `Enumerable` shouldn't be a pressing issue. (`CSV` and `Regex::MatchData` are notable exceptions in the standard library.)

2021-02-25 13:47 UTC, straight-shoota requested changes

2021-02-25 13:47 UTC, straight-shoota commented on src/compiler/crystal/syntax/parser.cr
> +          exp = Splat.new(exp).at(exp_location) if has_splat
Minor structural suggestion, but I think this code is better with two separate branches. The only shared expression is a single call.

```suggestion
          if @token.type == :"*"
            next_token_skip_space_or_newline
            location = @token.location
            exp = Splat.new(parse_op_assign_no_control).at(location)
          else
            exp = parse_op_assign_no_control
          end
```
Ditto below.

2021-04-15 17:35 UTC, HertzDevil commented
Instead of `__crystal_first` there is now `Enumerable.element_type`, other kinds of literal expansions refer to class methods in the prelude so this shouldn't be a problem. It might replace the `first_internal` helper I added in some other PRs too.

2021-05-25 13:43 UTC, straight-shoota approved these changes

2021-05-25 14:31 UTC, straight-shoota commented on src/enumerable.cr
> +  # NOTE: there should never be a need to call this method outside the standard library.
I don't think this should be a warning.
We could consider making this method nodoc, though. It's only internal API.

2021-06-01 05:05 UTC, HertzDevil commented
The PR currently doesn't allow non-`Enumerable` splats inside `Array`s because of `Array#concat(other : Enumerable)`'s type restriction (array literals expand to `concat`, not the more verbose `each` loop). Should we remove that type restriction?

2021-06-01 08:28 UTC, straight-shoota commented
I suppose this restriction is not really necessary. However, what type would implement a compatible `#each` interface an *not* include `Enumerable`? Practically, I don't see much impact.

2021-06-02 10:06 UTC, HertzDevil commented
`CSV`, `Enum` (flags enums only), `LLVM::FunctionCollection`, and `YAML::Nodes::Mapping`.

2021-06-04 19:59 UTC, asterite commented on src/compiler/crystal/codegen/codegen.cr
> +        if node.elements.any?(Splat)
Great use of this variant of `any?`! It actually reads really nice too :-)

2021-06-04 20:02 UTC, asterite approved these changes
I love this new feature! ❤️

2021-06-04 20:02 UTC, merged