Add `#exists?` Top-level Macro Method
crystal-lang/crystal pull request #10489
Opened 2021-03-10 02:35 UTC by toddsundsted

Useful when composing the name of a file to read from in a macro.

I use this in my Kemal applications to create a render helper that takes a file name and checks for various flavors of templates using the name:

```crystal
render "objects/index" # checks for and renders index.html.ecr, index.html.slang, etc.
```

The alternative is to use `#read_file?` as a check for existence. (Maybe there's another way that I'm missing.)

2021-03-10 15:04 UTC, toddsundsted commented
good suggestions! done!

2021-03-29 11:57 UTC, straight-shoota requested changes
If you would rename the macro to `file_exists?`, I think this is good to go.

2021-03-29 13:08 UTC, toddsundsted commented
@straight-shoota done!

2021-03-29 14:19 UTC, straight-shoota approved these changes

2021-07-18 12:10 UTC, closed without merging