Added from_json_object_key? to UUID
crystal-lang/crystal pull request #10517
Opened 2021-03-17 14:41 UTC by kalinon

Added the the required `from_json_object_key?` to UUID so that it can be used as a hash key.

2021-03-17 14:51 UTC, straight-shoota approved these changes

2021-03-17 14:53 UTC, kalinon commented
@straight-shoota thx. just pushed spec test as well.

2021-03-17 14:55 UTC, Blacksmoke16 requested changes

2021-03-17 14:55 UTC, Blacksmoke16 commented on spec/std/uuid/json_spec.cr
> +describe "UUID", focus: true do
```suggestion
describe "UUID" do
```

2021-03-17 14:55 UTC, Blacksmoke16 commented on spec/std/uuid/json_spec.cr
> +end
```suggestion
end

```

2021-03-17 14:55 UTC, Blacksmoke16 commented on src/uuid/json.cr
> +  # Deserializes the given JSON in *string* into a UUID instance
```suggestion
  # Deserializes the given JSON *key* into a `UUID`.
```

2021-03-17 14:56 UTC, kalinon commented on spec/std/uuid/json_spec.cr
> +end
fixed as well

2021-03-17 15:48 UTC, Sija commented on src/uuid/json.cr
> +  #
```suggestion
```

2021-03-20 15:00 UTC, sdogruyol approved these changes
Thank you @kalinon 🙏

2021-04-08 12:53 UTC, merged