Add refernces between String equality, comparison methods
crystal-lang/crystal pull request #10531
Opened 2021-03-22 15:59 UTC by straight-shoota

2021-03-22 16:09 UTC, vlazar requested changes

2021-03-22 16:09 UTC, vlazar commented on src/string.cr
> +  # Equality is chacked byte-per-byte: if any byte is different from the corresponding
```suggestion
  # Equality is checked byte-per-byte: if any byte is different from the corresponding
```

2022-08-18 13:07 UTC, HertzDevil commented on src/string.cr
> +  # byte, it returns `false`.
Upstream now has notes about invalid byte sequences here.

2022-12-09 08:24 UTC, caspiano approved these changes

2022-12-09 08:40 UTC, sdogruyol approved these changes
Thank you @straight-shoota 🙏

2022-12-11 20:07 UTC, merged