Add return type restrictions to JSON, YAML, XML
crystal-lang/crystal pull request #10581
Opened 2021-04-03 12:03 UTC by oprypin

2021-04-03 14:49 UTC, straight-shoota approved these changes

2021-04-04 09:40 UTC, Sija requested changes

2021-04-04 09:40 UTC, Sija commented on src/json/pull_parser.cr
> +  def read_begin_array : JSON::PullParser::Kind
No need to use the full path, ditto elsewhere.

```suggestion
  def read_begin_array : Kind
```

2021-04-05 11:33 UTC, straight-shoota commented
Why did you remove the restrictions on `read_{begin,end}_{array,object}` entirely?

2021-04-05 11:45 UTC, oprypin commented
@straight-shoota I have realized that those return value are not useful and accidental, they'd better be `Nil`, except I don't do backwards-incompatible changes here, so better just leave them as is.

2021-04-05 12:23 UTC, straight-shoota approved these changes

2021-06-07 09:11 UTC, merged