Updating aarch64 actions to use 1.0.0 images
crystal-lang/crystal pull request #10976
Opened 2021-07-20 22:30 UTC by beta-ziliani

Note: this is already late, as we need 1.1.0 images, but for the moment it should suffice.

2021-07-20 22:47 UTC, oprypin commented
Uuh duplicate of https://github.com/crystal-lang/crystal/pull/10814 ?

2021-07-21 08:34 UTC, straight-shoota approved these changes

2021-07-21 08:36 UTC, straight-shoota commented
@oprypin Nope. The other PR changed to `crystallang/crystal` which doesn't have aarch64 images. This keeps using the (unofficial) aarch64 images at `jhass/crystal` but with an updated version.

2021-07-21 09:23 UTC, vlazar requested changes

2021-07-21 09:23 UTC, vlazar commented on .github/workflows/aarch64.yml
> +        uses: docker://jhass/crystal:1.35.0-build
```suggestion
        uses: docker://jhass/crystal:1.0.0-build
```

2021-07-21 09:25 UTC, straight-shoota commented
Unfortunately, the aarch64 CI jobs keep failing more or less consistently and without any error indication.

2021-07-21 20:36 UTC, beta-ziliani commented
It isn't failing now, or at least, some are working that before weren't. But the x86 alpine one is failing (unrelated to this) 🤷

2021-07-21 22:10 UTC, straight-shoota commented
Only the build jobs pass. All the `*-test-*` aarch64 jobs are failing: https://github.com/crystal-lang/crystal/actions/runs/1053459506

2021-07-22 08:00 UTC, jhass commented
Seems like something had hang up, some of the VMs were showing significant CPU usage despite no job running at the moment. I rebooted all the VMs and reran the workflow, looks much better so far.

2021-07-22 08:49 UTC, straight-shoota commented
@jhass Looks like the aarch64 runners hang up again while running compiler specs (I don't think they should take over an hour for that, but we can wait a little longer to see if they might finish later).

2021-07-22 08:59 UTC, jhass commented
Well, they did take that long :)

2021-07-22 10:33 UTC, merged

2021-08-05 15:30 UTC, straight-shoota commented
This was apparently incomplete:

https://github.com/crystal-lang/crystal/blob/a8bc392ae80a91b96d3ba600fc38d5f266938025/.github/workflows/aarch64.yml#L36

2021-08-05 17:08 UTC, beta-ziliani commented
Oops. @jhass if you find yourself with time to update the images, it would be nice to have 1.1.1 version to compile the latest pulls. Thanks!

2021-08-06 07:54 UTC, jhass commented
@beta-ziliani These images just package up https://dev.alpinelinux.org/archive/crystal/. As you can see there's no archive there for 1.1.1 or 1.1.0. Feel free to find a different solution/way to build them, all the code used is at https://github.com/crystal-lang/crystal-infrastructure/tree/main/docker