Fix CI rules for building libiconv on Windows
crystal-lang/crystal pull request #11504
Opened 2021-11-28 16:32 UTC by HertzDevil

Fixes https://github.com/crystal-lang/crystal/pull/11480#issuecomment-980469203. Alternative to #11502.

The current repository that we use to build libiconv has no potential license issues, because it references the files in `libcharset/include`, never `srclib`: https://github.com/pffang/libiconv-for-Windows/blob/9b7aba8da6e125ef33912fa4412779279f204003/libiconv.vcxproj#L62-L63

This approach is also less error-prone because we are no longer editing the .vcxproj files in-place.

2021-11-28 17:54 UTC, oprypin approved these changes

2021-11-28 20:42 UTC, oprypin requested changes
Welp CI is failing

2021-11-29 00:02 UTC, HertzDevil commented
I think this is finally it

2021-11-29 07:34 UTC, oprypin approved these changes

2021-11-29 11:10 UTC, straight-shoota approved these changes

2021-11-30 10:19 UTC, merged

2023-05-15 22:20 UTC, HertzDevil commented
This workaround is no longer necessary after 2.11.0: https://gitlab.gnome.org/GNOME/libxml2/-/commit/530938b4870192d51fd0f01e564c12acc0f7acac