Expose additional GC prof stats fields
crystal-lang/crystal pull request #12003
Opened 2022-04-15 17:15 UTC by z64

In bdwgc 8.2.0, there are two additional prof_stats fields.
This updates the mapped crystal types to include these fields.

https://github.com/ivmai/bdwgc/blob/v8.2.0/include/gc.h#L812-L816

Example output:

    GC::ProfStats(
     @bytes_before_gc=844434288,
     @bytes_reclaimed_since_gc=1008096,
     @bytes_since_gc=825040,
     # new
     @explicitly_freed_bytes_since_gc=123808,
     @free_bytes=864256,
     @gc_no=1224,
     @heap_size=1695744,
     @markers_m1=3,
     @non_gc_bytes=0,
     # new
     @obtained_from_os_bytes=2088960,
     @reclaimed_bytes_before_gc=653709120,
     @unmapped_bytes=442368)

2022-04-15 17:27 UTC, z64 commented
If anyone would like to view these fields on the currently released crystal, you can use this alternate wrapper:

```cr
@[Extern]
struct ProfStatsExt
  alias Word = LibC::ULong
  getter heap_size : Word = 0
  getter free_bytes : Word = 0
  getter unmapped_bytes : Word = 0
  getter bytes_since_gc : Word = 0
  getter bytes_before_gc : Word = 0
  getter non_gc_bytes : Word = 0
  getter gc_no : Word = 0
  getter markers_m1 : Word = 0
  getter bytes_reclaimed_since_gc : Word = 0
  getter reclaimed_bytes_before_gc : Word = 0

  # NOTE(z64): added
  getter expl_freed_bytes_since_gc : Word = 0
  # NOTE(z64): added
  getter obtained_from_os_bytes : Word = 0
end

def gc_prof_stats_ext : ProfStatsExt
  stats = ProfStatsExt.new
  stats_ptr = pointerof(stats)

  LibGC.get_prof_stats(
    stats_ptr.unsafe_as(Pointer(LibGC::ProfStats)),
    sizeof(ProfStatsExt))

  stats
end
```

2022-04-15 18:01 UTC, straight-shoota commented
When those fields were introduced in bdwgc 8.2.0, that means these bindings wouldn't work with older versions, right?

2022-04-15 18:16 UTC, z64 commented
@straight-shoota Nothing will break. The API is designed for this:

```c
/* Atomically get GC statistics (various global counters).  Clients     */
/* should pass the size of the buffer (of GC_prof_stats_s type) to fill */
/* in the values - this is for interoperability between different GC    */
/* versions, an old client could have fewer fields, and vice versa,     */
/* client could use newer gc.h (with more entries declared in the       */
/* structure) than that of the linked libgc binary; in the latter case, */
/* unsupported (unknown) fields are filled in with -1.  Return the size */
/* (in bytes) of the filled in part of the structure (excluding all     */
/* unknown fields, if any).                                             */
GC_API size_t GC_CALL GC_get_prof_stats(struct GC_prof_stats_s *,
                                        size_t /* stats_sz */);
```
https://github.com/ivmai/bdwgc/blob/v8.2.0/include/gc.h#L819-L829

Since the bindings use unsigned `ULong`, the unknown values will be shown in Crystal as *exactly* `-1_i64.unsafe_as(UInt64)` / `18446744073709551615`, for example:

```
 @obtained_from_os_bytes=18446744073709551615,
```

We could detect this in the wrapper method and set the field to `0`, if that would be preferable.

2022-04-15 18:27 UTC, z64 commented
For instance, something like:

```diff
--- a/src/gc/boehm.cr
+++ b/src/gc/boehm.cr
@@ -224,6 +224,19 @@ module GC
   def self.prof_stats
     LibGC.get_prof_stats(out stats, sizeof(LibGC::ProfStats))

+    # get_prof_stats will set unknown struct fields to -1
+    unknown_field_bit_pattern = ~0_u64
+
+    # Present in GC >= 8.2.0
+    if stats.explicitly_freed_bytes_since_gc == unknown_field_bit_pattern
+      stats.explicitly_freed_bytes_since_gc = 0
+    end
+
+    # Present in GC >= 8.2.0
+    if stats.obtained_from_os_bytes == unknown_field_bit_pattern
+      stats.obtained_from_os_bytes = 0
+    end
+
```

2022-04-15 18:35 UTC, z64 commented
We can also read GC version at runtime and act accordingly - there is a function for that. But I think the bit pattern method is preferable.

2022-04-15 18:43 UTC, straight-shoota commented
That's great.

But it might actually be best to leave the unknown indicator value in place. Or make the field nilable and use `nil` to represent an unknown value. But changing *unknown* to `0` doesn't sound like a very good idea.

2022-04-15 18:45 UTC, z64 commented
Ok. Personally I'm fine without intervening on Crystal's end. If anyone would like to do otherwise, please feel free to modify this PR.

2022-08-13 17:48 UTC, HertzDevil requested changes
Leaving them as `-1` is probably fine, since `GC::ProfStats` is inherently implementation-specific. 

The new fields are still missing in `src/gc/none.cr`'s implementation of the same method though.

2022-08-13 17:48 UTC, HertzDevil commented on src/gc/boehm.cr
> +    obtained_from_os_bytes : Word
These types are now also `UInt64` after #11963.

2022-09-10 08:20 UTC, closed without merging