Respect `%CC%` on Windows
crystal-lang/crystal pull request #13376
Opened 2023-04-21 18:08 UTC by HertzDevil

Resolves #12988.

2023-04-21 23:45 UTC, oprypin approved these changes

2023-04-24 09:17 UTC, straight-shoota commented on src/compiler/crystal/compiler.cr
> +    CL = ENV["CC"]? || "cl.exe"
I think the naming of these constants is a bit confusing when `CL` is `ENV["CC"]`. 
They are probably pretty unnecessary anyway. The single use is in `linker_command`. So it doesn't even make much sense to have a constant.

But I'm fine with merging this and refactor afterwards.

2023-04-24 10:06 UTC, straight-shoota approved these changes

2023-04-25 09:31 UTC, straight-shoota requested changes

2023-04-25 09:31 UTC, straight-shoota commented on src/compiler/crystal/compiler.cr
> +        linker = MSVC
```suggestion
        linker = MSVC_LINKER
```

2023-04-26 16:20 UTC, merged