Fix return type of Iterator#chunk and Enumerable#chunks without `Drop`
crystal-lang/crystal pull request #13506
Opened 2023-05-26 09:35 UTC by straight-shoota

resolves #13396

2023-05-26 09:36 UTC, straight-shoota commented on src/enumerable.cr
> +    chunks_internal(block) { |*kv| res << kv }
This change is due to #13437, but it also makes sense on its own.

2023-06-05 13:51 UTC, HertzDevil requested changes

2023-06-05 19:08 UTC, HertzDevil approved these changes

2023-06-05 19:08 UTC, Sija commented on src/enumerable.cr
> +      def acc(key, val, &)
Shouldn't this be private?

```suggestion
      private def acc(key, val, &)
```

2023-06-05 19:22 UTC, straight-shoota commented on src/enumerable.cr
> +      def acc(key, val, &)
No, it's called externally.

2023-06-14 13:11 UTC, merged