Fix avoid calling realpath of parent crystal
crystal-lang/crystal pull request #13596
Opened 2023-06-22 21:08 UTC by straight-shoota

Resolves #13592

2023-06-23 10:56 UTC, HertzDevil requested changes

2023-06-23 10:56 UTC, HertzDevil commented on bin/crystal
> +PARENT_CRYSTAL_COMMAND_REALPATH=$(realpath "$PARNET_CRYSTAL_COMMAND" 2> /dev/null)
`PARNET_CRYSTAL_COMMAND` seems to be a typo

2023-06-23 11:52 UTC, straight-shoota commented
Fixed.

The difference is that the parent crystal command resolved with `realpath` is now only used to determine wether it points to the wrapper script itself.
When calling parent crystal, the original path is used, without `realpath`:

https://github.com/crystal-lang/crystal/blob/78b2d35dfefed2d133b7576ae1cd81cba1d9cd4a/bin/crystal#L196

2023-06-23 12:02 UTC, HertzDevil approved these changes

2023-06-26 15:26 UTC, HertzDevil approved these changes

2023-06-27 18:01 UTC, merged