yield key in Hash#transform_values, Hash#transform_values! and yield value in Hash#transform_keys
crystal-lang/crystal pull request #13608
Opened 2023-06-29 01:14 UTC by baseballlover723

Fixes #13581

2023-06-29 03:44 UTC, Sija commented on spec/std/hash_spec.cr
> +    expected_values = ["a", "b", "c"]
```suggestion
    expected_values = h1.values
```

2023-06-29 03:44 UTC, Sija commented on spec/std/hash_spec.cr
> +    expected_keys = ["a", "b", "c"]
```suggestion
    expected_keys = h1.keys
```

2023-06-29 03:44 UTC, Sija commented on spec/std/hash_spec.cr
> +    expected_keys = ["a", "b", "c"]
```suggestion
    expected_keys = h1.keys
```

2023-06-29 08:58 UTC, straight-shoota commented on spec/std/hash_spec.cr
> +    h2.should eq({2 => "a", 3 => "b", 4 => "c"})
Food for thought: Maybe a simpler implementation could combine key and value?
```suggestion
    h1.transform_keys{ |k, v| "#{k}#{v}" }.should eq({"2a" => "a", "3b" => "b", "4c" => "c"})
```
The same can be applied to all other tests.

2023-06-29 13:29 UTC, beta-ziliani requested changes
Thanks for the contribution @baseballlover723! Let me add to what was said that the types of the blocks are not respecting the change, and it would be great if the docs can reflect the change too with a little comment.

Let us know if you want us to take over, or if you prefer to take it to completion.

2023-06-29 15:05 UTC, baseballlover723 commented
@beta-ziliani I'd prefer to take it to completion if possible. To clarify, is what you're asking me to do to update the function defs from `def transform_values(& : V -> V2) : Hash(K, V2) forall V2` -> `def transform_values(& : V, K -> V2) : Hash(K, V2) forall V2`? I was surprised that it worked even without updating the type blocks.

I'll also update the docs as well, though I don't really want to change the example code structure, so the added value will just be unused in the example block.

2023-06-29 15:14 UTC, beta-ziliani commented
yes, exactly, that's what I mean. About the documentation, I just meant to add a line stating that the value/key are also yielded to the block

2023-06-29 15:20 UTC, baseballlover723 commented
@beta-ziliani updated the docs, let me know if the wording is ok with you.

2023-06-29 16:55 UTC, straight-shoota commented on src/hash.cr
> +  # The block optionally yields the value as well
It isn't mentioned previously that the block yields the key, so I think both should be mentioned:
```suggestion
  # The block yields key and value.
```

2023-06-29 19:38 UTC, beta-ziliani approved these changes
Awesome, thanks @baseballlover723 !

2023-07-05 09:00 UTC, straight-shoota commented on src/hash.cr
> +  # hash.transform_keys { |key, _value| key.to_s } # => {"a" => 1, "b" => 2, "c" => 3}
This addition isn't really necessary. Unused block parameters can simply be omitted, so I don't think it's useful to write it it with an underscore prefix.
```suggestion
  # hash.transform_keys { |key| key.to_s } # => {"a" => 1, "b" => 2, "c" => 3}
```

Ditto below.

2023-07-06 07:58 UTC, straight-shoota approved these changes

2023-07-22 13:19 UTC, merged