infra(make): Add `generate_data` target for running generator scripts
crystal-lang/crystal pull request #13700
Opened 2023-07-24 13:25 UTC by straight-shoota

This target makes it easy to run all generator scripts at once. I want to add this as a check to the release process.

2023-07-24 16:56 UTC, HertzDevil reviewed
I think `scripts/generate_windows_zone_names.cr` is the only script that cannot work on Windows (i.e. cannot be called inside `Makefile.win`), because it still requires live tzdata on the host running the script

2023-07-24 17:41 UTC, straight-shoota commented
I think it should be possible to have that working on Windows with a copy of tzdata.

2023-07-24 17:49 UTC, HertzDevil commented
By the way, if we want to avoid tzdata entirely, the standard abbreviation names are also in CLDR, like this: https://github.com/unicode-org/cldr/blob/b24157695397c4c3d2d058c201da92d10c9d9022/common/main/en_NZ.xml#L165

2023-09-20 20:01 UTC, HertzDevil requested changes

2023-09-20 20:01 UTC, HertzDevil commented on Makefile.win
`Makefile.win` should use `\` as the directory separator consistently

2023-09-20 20:42 UTC, HertzDevil approved these changes

2023-09-23 07:21 UTC, merged