Optimize the constructors of `Time::Span`
crystal-lang/crystal pull request #13807
Opened 2023-09-17 05:13 UTC by erdian718

1. Avoid arithmetic overflow exception.
2. Remove unnecessary type conversions.
3. Remove unnecessary normalization.

Closes #13797

2023-09-17 11:10 UTC, straight-shoota approved these changes

2023-09-18 17:48 UTC, HertzDevil requested changes

2023-09-18 17:48 UTC, HertzDevil commented on src/time/span.cr
> +    @seconds = seconds.to_i64 + nanoseconds.tdiv(NANOSECONDS_PER_SECOND)
If `nanoseconds` is a `BigInt`, then `@seconds` would also be a `BigInt`:

```suggestion
    @seconds = seconds.to_i64 + nanoseconds.tdiv(NANOSECONDS_PER_SECOND).to_i64
```

2023-09-19 11:32 UTC, HertzDevil approved these changes

2023-09-20 13:55 UTC, merged