Fix block parameter unpacking inside macros
crystal-lang/crystal pull request #13813
Opened 2023-09-19 14:22 UTC by HertzDevil

Fixes #13742.

2023-09-19 14:39 UTC, hotty316 requested changes
58+{+9192505779629}

2023-09-19 15:17 UTC, straight-shoota commented
FTR: The regression was introduced in https://github.com/crystal-lang/crystal/pull/11597 (not yet released)

2023-09-19 15:17 UTC, straight-shoota approved these changes

2023-09-19 18:21 UTC, straight-shoota approved these changes

2023-09-20 14:55 UTC, Blacksmoke16 commented
I applied this patch on latest commit on master and tried the Athena specs again and now got:

```cr
In src/components/framework/src/ext/routing/annotation_route_loader.cr:231:128

 231 | [{ATHA::QueryParam, "ATH::Params::QueryParam".id}, {ATHA::RequestParam, "ATH::Params::RequestParam".id}].each do |(param_ann, param_class)|
                                                                                                                          ^---------
Error: undefined macro variable '__temp_113'
```

So there still seems to be another issue. I'll see about reducing it and will create another ticket.

2023-09-20 15:26 UTC, Blacksmoke16 commented
Actually no, reproduction for this is the same as #13742, but just call `test` macro twice. Because of that I don't think it needs its own ticket?

2023-09-20 16:46 UTC, HertzDevil commented
Apparently the normalizer _mutates_ `Block` nodes in-place if they contain unpacked parameters, without emptying `Block#unpacks`, so calling the same macro twice will also create the multi-assign expression twice, but overwrite the previous temporary packed parameter:

```crystal
do |__temp_4|
  k, v = __temp_4
  k, v = __temp_1
  k
end
```

2023-09-20 16:52 UTC, straight-shoota approved these changes

2023-09-20 17:13 UTC, Blacksmoke16 commented
Awesome! Testing again with that latest commit and all Athena specs pass. Thanks!

2023-09-20 17:48 UTC, straight-shoota commented
Specs are failing though.

2023-09-20 19:51 UTC, HertzDevil commented
So `Block#unpacks` is needed by the main visitor it seems. I have replaced that with a different check

2023-09-20 20:07 UTC, straight-shoota approved these changes

2023-09-24 16:29 UTC, merged