Darwin: Only set FD_CLOEXEC when creating a socket FD
crystal-lang/crystal pull request #14650
Opened 2024-06-01 07:13 UTC by carlhoerberg

Not when an existing FD is passed to Socket.new

2024-06-01 07:14 UTC, carlhoerberg commented
Follow up on https://github.com/crystal-lang/crystal/pull/14632#pullrequestreview-2080836656

2024-06-01 07:57 UTC, straight-shoota approved these changes

2024-06-01 07:59 UTC, straight-shoota requested changes

2024-06-01 07:59 UTC, straight-shoota commented on src/crystal/system/unix/socket.cr
> +      fcntl(fd, LibC::F_SETFD, LibC::FD_CLOEXEC)
**issue:** When using the instance method, there's no `fd` argument:

```suggestion
      fcntl(LibC::F_SETFD, LibC::FD_CLOEXEC)
```

2024-06-03 12:27 UTC, ysbaddaden commented
I notice some issues with this change: when we create the socket the `@handle` ivar isn't set and calling `#fcntl` will fail (see CI) but we also set CLOEXEC for plain `fd` (e.g. `Socket.new(fd, ...)` which is used in `UNIXSocket.pair` for example.

2024-06-03 12:53 UTC, straight-shoota commented
> when we create the socket the `@handle` ivar isn't set and calling `#fcntl` will fail (see CI)

Yeah I think we need to use `LibC.fcntl(fd, ...)` like before to fix the current failure. The file descriptor is not assigned yet, so we cannot use `#fcntl`.

> we also set CLOEXEC for plain `fd` (e.g. `Socket.new(fd, ...)` as called from `UNIXSocket.pair` or `Socket#accept?` for example.

Yes, that's the current behaviour. But I believe it's wrong. We probably shouldn't autoclose a file descriptor that's coming from outside the process. Only close what we opened ourselves.
That means all uses in stdlib like `Socket#accept?` need to be updated to explicitly set close on exec.

However, I'm wondering if this isn't too bad a silent breaking change in behaviour... 🤔

2024-06-03 13:46 UTC, ysbaddaden commented
I agree: it may not be the best API, but security-wise it doesn't sound like a bad practice to always close file descriptors on exec... and maybe always calling `fcntl` ain't a bad idea instead of setting `O_CLOEXEC`. If you need it to not be closed on exec, you can always call `fcntl` to disable the flag.

2024-06-03 18:28 UTC, Sija commented on src/crystal/system/unix/socket.cr
> +      raise ::Socket::Error.from_errno("fcntl() failed") if r == -1
Suggestion: avoid using one letter names for clarity.

```suggestion
      ret = LibC.fcntl(fd, LibC::F_SETFD, LibC::FD_CLOEXEC)
      raise ::Socket::Error.from_errno("fcntl() failed") if ret == -1
```

2024-06-03 19:23 UTC, straight-shoota approved these changes

2024-06-04 07:30 UTC, ysbaddaden commented
The following methods (at least) must also be fixed to set `FD_CLOEXEC` for darwin targets:

- `Socket#accept?`
- `UNIXSocket#accept?`
- `UNIXSocket.pair`

Why Apple wouldn't implement the `O_CLOEXEC` flag is beyond me :face_exhaling:

2024-06-04 07:31 UTC, ysbaddaden requested changes
The following methods (at least) must also be fixed to set `FD_CLOEXEC` for darwin targets:

- `Socket#accept?`
- `UNIXSocket#accept?`
- `UNIXSocket.pair`

Maybe there should be a system method to set `FD_CLOEXEC` on a given `fd` to avoid repeating the same `LibC.fcntl` call? Something like `Crystal::System::FileDescriptor.set_close_on_exec(fd : Int32) : Nil`.

Why Apple wouldn't implement the ~~`O_CLOEXEC`~~ `SOCK_CLOEXEC` flag is beyond me :face_exhaling:

2024-06-04 08:03 UTC, straight-shoota commented
Yeah, I suppose we should also setup specs for those methods.

@carlhoerberg If you want to go on, please continue. But we'll be happy to take over these final steps if you prefer.

2024-06-04 10:04 UTC, carlhoerberg commented
Go for it! :)

2024-06-14 10:44 UTC, closed without merging