Add support for IPv6 scoped addresses (RFC4007)
crystal-lang/crystal pull request #15263
Opened 2024-12-10 12:07 UTC by foxxx0

In order to translate interface names in such scoped addresses the
 required `LibC` binding to `if_nametoindex()` has been added.
 This method obviously only works for interfaces (devices) that are
 actually present on the system.

 The binding for the reverse operation `if_indextoname()` has also been
 added, although its usage is a bit more cumbersome due to `LibC::Char*`
 buffer handling. The necessary buffer length has been placed into the
 constant `LibC::IF_NAMESIZE`, which appears to be `16u8` on unix-like
 systems and `257u16` on windows.
 This could potentially be reworked via a preprocessor block at
 compile-time as indicated by some folks over on discord, I currently do
 not know how to achieve that though.

Scoped identifiers are only valid for link-local (`fe80::`) addresses, e.g. `fe80::1%eth0`

References:
  - https://datatracker.ietf.org/doc/html/rfc4007

Fixes #15264 .

2024-12-10 12:26 UTC, straight-shoota commented
Could you please open an issue as a feature request first? We ask this to separate high-level discussion of the feature (in the issue discussion) from details of this specific PR (PR discussion).

I'm marking this PR as draft for now.

2024-12-10 14:03 UTC, foxxx0 commented
ah well, shame on me.

I've just created https://github.com/crystal-lang/crystal/issues/15264 now to discuss the feature itself.

2025-04-12 09:30 UTC, foxxx0 commented
Alright, here we go.

Not sure why, but something is not happy in the workflow runs in my fork.
 - `AArch64` is always skipped immediately
 - `x86_64-windows-dlls` and `x86_64-windows-libs` fail building `libiconv`

Apart from that the remaining workflows appear to be happy with it.

Let me know if you'd like more comments in the added code or want something changed.

2025-04-14 14:26 UTC, straight-shoota requested changes

2025-04-14 14:26 UTC, straight-shoota commented on src/socket/address.cr
>          addr = v4(v4_fields, port.to_u16!)
**suggestion:** The `#inspect` output should include zone info as well (when available).

2025-04-14 14:26 UTC, straight-shoota commented on src/socket/address.cr
> +        if v6_fields[0] == 0xfe80 && !zone_part.empty?
**issue:** Like in the v4 branch, this means we're silently dropping any zone part if the address is not link-local. I believe an invalid zone part should better always be an error.

2025-04-14 14:26 UTC, straight-shoota commented on src/socket/address.cr
> +            zone_id_parsed = LibC.if_nametoindex(zone_part).not_nil!
**issue:** `not_nil!` is unnecessary.
```suggestion
            zone_id_parsed = LibC.if_nametoindex(zone_part)
```

2025-04-14 23:37 UTC, foxxx0 commented on src/lib_c/x86_64-windows-msvc/c/foobar
correct. unsure how that slipped past me. removed in a separate commit, can be squashed / fixup'ed if desired.

2025-04-14 23:37 UTC, foxxx0 commented on spec/std/socket/address_spec.cr
> +      Socket::IPAddress.new("fe80::4545", 0).link_local_interface.should eq nil
adjusted.

2025-04-14 23:38 UTC, foxxx0 commented on src/socket/address.cr
> +        if v6_fields[0] == 0xfe80 && !zone_part.empty?
Agree. I've reworked the address-parsing part and this is now much more strict.

2025-04-14 23:38 UTC, foxxx0 commented on src/socket/address.cr
>          addr = v4(v4_fields, port.to_u16!)
Great idea, added.

2025-04-14 23:38 UTC, foxxx0 commented on spec/std/socket/address_spec.cr
> +      ifname.should eq loopback_iface
adjusted.

2025-04-14 23:39 UTC, foxxx0 commented on src/socket/address.cr
> +            zone_id_parsed = zone_part.to_u32
agreed, I've cleaned up the parsing part and removed the double parsing and extra variable.

2025-04-14 23:39 UTC, foxxx0 commented on src/socket/address.cr
> +      return nil unless (@family == Socket::Family::INET6 && link_local?)
adjusted.

2025-04-14 23:40 UTC, foxxx0 commented on src/socket/address.cr
> +            zone_id_parsed = LibC.if_nametoindex(zone_part).not_nil!
fixed. parsing logic has been reworked and with it there no longer is a `.not_nil!`.

2025-04-14 23:41 UTC, foxxx0 commented on src/socket/address.cr
> +      addr_part, _, scope_part = address.partition('%')
Instead of adding specs for this, I've reworking the parsing code and the `address.partition('%')` is now only attempted when parsing as v4 fails. Thus it no longer happens for v4 addresses.

2025-04-14 23:42 UTC, foxxx0 commented on src/lib_c/x86_64-windows-msvc/c/foobar
correct. unsure how that slipped past me. removed in a separate commit, can be squashed / fixup'ed if desired.

2025-04-14 23:44 UTC, foxxx0 commented
Thanks for the detailed review and constructive feedback/suggestions.
I've updated the branch/PR accordingly.

Following the contributing guidelines I have done so with separate commits but I'd be happy to rebase+squash/fixup if desired for a "cleaner" history before merging into `master`.

2025-04-15 00:59 UTC, Sija commented on src/socket/address.cr
> +    # Socket::IPAddress.new("fe80::4567:8:9%eth0", 443)        # => Socket::IPAddress([fe80::4567:8:9]:443)
```suggestion
    # Socket::IPAddress.new("fe80::4567:8:9%eth0", 443)        # => Socket::IPAddress([fe80::4567:8:9%eth0]:443)
```

2025-04-15 00:59 UTC, Sija commented on src/socket/address.cr
> +            raise ArgumentError.new("Zoned/scoped IPv6 addresses are only allowed for link-local (supplied '#{addr_part}' is not within fe80::/10).")
Exception messages are commonly written without a trailing dot.

```suggestion
            raise ArgumentError.new("Zoned/scoped IPv6 addresses are only allowed for link-local (supplied '#{addr_part}' is not within fe80::/10)")
```

2025-04-15 00:59 UTC, Sija commented on src/socket/address.cr
> +              raise ArgumentError.new("Invalid IPv6 link-local zone index '#{zone_part}' in address '#{address}'.") unless zone_id.positive?
ditto

```suggestion
              raise ArgumentError.new("Invalid IPv6 link-local zone index '#{zone_part}' in address '#{address}'") unless zone_id.positive?
```

2025-04-15 00:59 UTC, Sija commented on src/socket/address.cr
> +              raise ArgumentError.new("IPv6 link-local zone interface '#{zone_part}' not found (in address '#{address}').") unless zone_id.positive?
ditto

```suggestion
              raise ArgumentError.new("IPv6 link-local zone interface '#{zone_part}' not found (in address '#{address}')") unless zone_id.positive?
```

2025-04-15 07:50 UTC, straight-shoota commented on src/socket/address.cr
> +      addr_part, _, scope_part = address.partition('%')
Still wouldn't hurt to add some specs for v4 adresses to explicitly encode this behaviour.

2025-04-15 08:08 UTC, foxxx0 commented on src/socket/address.cr
> +      addr_part, _, scope_part = address.partition('%')
Fair, I've added two additional specs for invalid v4 addrs that expect an exception to be raised.

2025-04-15 08:09 UTC, foxxx0 commented on src/socket/address.cr
> +    # Socket::IPAddress.new("fe80::4567:8:9%eth0", 443)        # => Socket::IPAddress([fe80::4567:8:9]:443)
Fixed and clarified the RFC4007 section in the comment as well.

2025-04-15 08:09 UTC, foxxx0 commented on src/socket/address.cr
> +              raise ArgumentError.new("Invalid IPv6 link-local zone index '#{zone_part}' in address '#{address}'.") unless zone_id.positive?
Fixed.

2025-04-15 08:09 UTC, foxxx0 commented on src/socket/address.cr
> +              raise ArgumentError.new("IPv6 link-local zone interface '#{zone_part}' not found (in address '#{address}').") unless zone_id.positive?
Fixed.

2025-04-15 09:31 UTC, straight-shoota reviewed
Don't worry about squash/rebase. We do that when merging.
Commit history in the PR is best left as is.

2025-04-15 09:31 UTC, straight-shoota commented on src/socket/address.cr
> +    # using #link_local_interface on the IPAddress object.
**suggestion:** Wrap references to methods and types in backticks to generate links.

```suggestion
    # in the `#inspect` representation. The interface name can be retrieved later
    # using `#link_local_interface` on the `IPAddress` object.
```

2025-04-15 09:31 UTC, straight-shoota commented on src/socket/address.cr
> +        addr_part, _, zone_part = address.partition('%')
**performance:** So far, the parsing algorithm is allocation-free. This `partition` introduces three string allocations, which should be avoidable.
A simple improvement could be to look for the byteindex of `%` and take a subslice of `address`, which we can then pass to `parse_v6_fields?` (the algorithm is based on `Slice`).
Parsing the zone_part into an int probably still requires a string allocation because there's no method for parsing from a slice (c.f. #6389).

We could also consider moving the entire parsing logic into `parse_v6_fields?`.
But I suppose some separation might actually be could. But there could be some more integration, for example that `parse_v6_fields?` stops consuming the slice when it reaches `%` and returns the remaining subslice (or index) for further processing in the constructor. This would remove iterating the string just to find the byteindex of `%`.

2025-04-15 09:31 UTC, straight-shoota commented on src/socket/address.cr
> +          if v6_fields[0] == 0xfe80 && !zone_part.empty?
**suggestion:** Merging these two condition should simplify the control flow.

```suggestion
          if zone_part.empty?
            zone_id = 0u32
          else
            if v6_fields[0] != 0xfe80
              raise ArgumentError.new("Zoned/scoped IPv6 addresses are only allowed for link-local (supplied '#{addr_part}' is not within fe80::/10)")
            end
```

2025-04-15 09:31 UTC, straight-shoota commented on spec/std/socket/address_spec.cr
> +      expect_raises(ArgumentError, "Zoned/scoped IPv6 addresses are only allowed for link-local (supplied 'fd00::abcd' is not within fe80::/10)") do
**issue:** The documentation of `IPAddress.new` states it raises `Socket::Error` if the address is invalid.
So we should raise that error type instead of `ArgumentError` (here and everywhere else).

2025-04-15 21:57 UTC, foxxx0 commented on src/socket/address.cr
> +    # using #link_local_interface on the IPAddress object.
Fixed.

2025-04-15 21:59 UTC, foxxx0 commented on src/socket/address.cr
> +        addr_part, _, zone_part = address.partition('%')
I have given your index-passing idea within `parse_v6_fields?` a try in the latest commit, please have a look if that matches what you had in mind.

2025-04-15 21:59 UTC, foxxx0 commented on src/socket/address.cr
> +          if v6_fields[0] == 0xfe80 && !zone_part.empty?
With the parsing rework I have simplified these.

2025-04-15 21:59 UTC, foxxx0 commented on spec/std/socket/address_spec.cr
> +      expect_raises(ArgumentError, "Zoned/scoped IPv6 addresses are only allowed for link-local (supplied 'fd00::abcd' is not within fe80::/10)") do
fixed.

2025-04-15 22:30 UTC, foxxx0 commented on src/socket/address.cr
> +        addr_part, _, zone_part = address.partition('%')
It was bothering me too much and I've added one more commit that changes the "index" approach to the subslice one. I much prefer it that way. Let me know what you think.

2025-04-16 08:41 UTC, foxxx0 commented on src/socket/address.cr
> +            zone_sep_idx = j
I was sure there was a way to calculate it when needed but wasn't able to piece it together myself. Thanks for clarifying.
Fixed.

2025-04-16 09:12 UTC, straight-shoota approved these changes
Look good. :+1:
I have some further small suggestions for improvements, if you can still bear with me. 
That's totally optional though, the PR is good to merge as is.

2025-04-16 09:12 UTC, straight-shoota commented on src/socket/address.cr
> +      { fields, zone_sep_idx.nil? ? nil : bytes[(zone_sep_idx + 1)..(bytes.size - 1)] }
**polish:** We can omit the end index for the subslice. It's implict.
```suggestion
      { fields, zone_sep_idx.nil? ? nil : bytes[(zone_sep_idx + 1)..] }
```

This would also be a good use case for `Slice#+`:
```suggestion
      { fields, zone_sep_idx.nil? ? nil : bytes + zone_sep_idx + 1 }
```

Even better, instead of storing an index, we can use a direct pointer to the zone index: `zone_ptr = ptr + 1` and construct a slice from it.
```suggestion
      { fields, zone_ptr.nil? ? nil : Bytes.new(zone_ptr, finish - zone_ptr) }
```

The code can also be simplified by assigning the slice directly to the local variable, which we can then use for the return value. This eliminates the extra nil check in the result.
```cr
if ...
 zone_slice = Bytes.new(ptr + 1, finish - ptr - 1)
end
# ...
{ fields, zone_slice }
```

2025-04-16 09:12 UTC, straight-shoota commented on src/socket/address.cr
> +    private def self.parse_v6_fields?(bytes : Bytes) : Tuple(UInt16[8]?, Slice(UInt8)?)
**polish:** This is a minor detail, but the return type `Tuple(UInt16[8], Slice(UInt8)?)?` might be a bit more convenient. Early returns would continue return just `nil` instead of `{ nil, nil }`.
The call site needs one extra step to first check if the result is nil and then deconstruct the tuple.

2025-04-16 10:51 UTC, foxxx0 commented on src/socket/address.cr
> +      { fields, zone_sep_idx.nil? ? nil : bytes[(zone_sep_idx + 1)..(bytes.size - 1)] }
Thanks for the detailed explanation and walking me through your though process. I'm always eager to learn so this is really appreciated.

I've implemented your simplified suggestion now.

2025-04-16 10:52 UTC, foxxx0 commented on src/socket/address.cr
> +    private def self.parse_v6_fields?(bytes : Bytes) : Tuple(UInt16[8]?, Slice(UInt8)?)
Good idea, I did find the `{ nil, nil }` return for malformed inputs a bit cumbersome indeed. That one extra step in the caller shouldn't be an issue since it's a private method and only referenced twice.

I've adjusted the code accordingly.

2025-04-16 11:02 UTC, straight-shoota approved these changes

2025-04-16 11:47 UTC, Sija approved these changes

2025-05-13 22:32 UTC, bcardiff approved these changes

2025-05-15 08:28 UTC, ysbaddaden commented on src/socket/address.cr
> +      String.new(buf.to_unsafe)
This might need to be extracted as a `Crystal::System::Socket.link_local_interface(zone_id)` method. Win32 happens to use the same API as POSIX, but WASI doesn't implement this for example, and should raise a `NotImplementedError` exception.

2025-05-15 08:35 UTC, ysbaddaden commented on src/socket/address.cr
> +    def self.v6(x0 : Int, x1 : Int, x2 : Int, x3 : Int, x4 : Int, x5 : Int, x6 : Int, x7 : Int, *, port : Int, zone_id : UInt32 = 0u32) : self
**Polish**: that should accept any Int and cast:

```suggestion
    def self.v6(x0 : Int, x1 : Int, x2 : Int, x3 : Int, x4 : Int, x5 : Int, x6 : Int, x7 : Int, *, port : Int, zone_id : Int32 = 0) : self
```

2025-05-15 08:36 UTC, ysbaddaden commented on src/socket/address.cr
> +    def self.v6(fields : UInt16[8], port : UInt16, zone_id : UInt32 = 0u32) : self
```suggestion
    def self.v6(fields : UInt16[8], port : UInt16, zone_id : Int = 0) : self
```

2025-05-15 08:40 UTC, ysbaddaden commented on src/socket/address.cr
> +      LibC.if_indextoname(@zone_id, buf)
**Issue**: the call may fail with `ENXIO`.

2025-05-16 20:20 UTC, foxxx0 commented
> Thanks for coping with all the changes, though I found a few more things to polish (sorry).
> 
> One thing I'm wondering, though is whether `zone_id` should really be an UInt32. We try to avoid unsigned integers in the stdlib. Is it possible for it to be larger than `Int32::MAX`?

The reason I went with `UInt32` is to match the `sockaddr_in6` struct datatypes:
```c
struct sockaddr_in6 {
   sa_family_t     sin6_family;   /* AF_INET6 */
   in_port_t       sin6_port;     /* port number */
   uint32_t        sin6_flowinfo; /* IPv6 flow information */
   struct in6_addr sin6_addr;     /* IPv6 address */
   uint32_t        sin6_scope_id; /* Scope ID (new in Linux 2.4) */
};
```

I do not think there is a way that this would ever exceed `Int32::MAX` as I really doubt anyone to have more than `2^31` network devices concurrently enumerated by the kernel.

However, I don't really grasp why unsiged integers in the stdlib *should?* be avoided. Would you be able to provide some reasoning for that? Otherwise I'd personally be more inclined to have `zone_id` match the type of `sockaddr_in6.sin6_scope_id`.

I'll go through the other remarks now and adjust accordingly.

2025-05-16 20:45 UTC, foxxx0 commented on src/socket/address.cr
> +      LibC.if_indextoname(@zone_id, buf)
Agreed, but would you be able to elaborate on what you expect to happen in such cases? Look at `Errno.valu` after the `LibC.if_indextoname` call and raise an exception if `!= NONE`?

2025-05-16 20:53 UTC, foxxx0 commented on src/socket/address.cr
> +      LibC.if_indextoname(@zone_id, buf)
I've adjusted the method to include
```diff
+      if Errno.value != Errno::NONE
+        raise Error.new("Failed to look up interface name for index #{zone_id} (#{Errno.value})")
+      end
```
I hope that's what you had in mind, if not please explain. :)

2025-05-16 20:53 UTC, foxxx0 commented on spec/std/socket/address_spec.cr
> +      Socket::IPAddress.new("fe80::4545", 0).link_local_interface.should be_nil
Having such an IPv6 address object instantiated doesn't pose an issue in itself. However, when trying to bind a socket with such an instance will then result in an appropriate error (`No such device (Socket::BindError)`).

If the `zone_id` property cannot find a corresponding network interface via `LibC.if_indextoname`, it will now raise a `Socket::Error`.

2025-05-16 20:58 UTC, foxxx0 commented on src/socket/address.cr
> +      String.new(buf.to_unsafe)
You're suggesting to move that helper method out of `Socket::Address` into the `Crystal::System::Socket` module?
We could also add a macro to the beginning of the method, e.g.:
```crystal
    def link_local_interface : String | Nil
      {% if flag?(:wasm32) %}
        raise NotImplementedError.new "Socket::Address.link_local_interface"
      {% end %}
```

2025-05-16 21:00 UTC, foxxx0 commented on src/socket/address.cr
> +    def self.v6(fields : UInt16[8], port : UInt16, zone_id : UInt32 = 0u32) : self
Depends on type discussion/question in https://github.com/crystal-lang/crystal/pull/15263#issuecomment-2887607827

2025-05-16 21:00 UTC, foxxx0 commented on src/socket/address.cr
> +    def self.v6(x0 : Int, x1 : Int, x2 : Int, x3 : Int, x4 : Int, x5 : Int, x6 : Int, x7 : Int, *, port : Int, zone_id : UInt32 = 0u32) : self
Depends on type discussion/question in https://github.com/crystal-lang/crystal/pull/15263#issuecomment-2887607827

2025-05-16 21:00 UTC, foxxx0 commented on src/socket/address.cr
> +    # also only keep the interface index around.
implemented.

2025-05-16 21:01 UTC, foxxx0 commented on src/socket/common.cr
> +  require "c/net/if"
fixed

2025-05-16 21:01 UTC, foxxx0 commented on src/lib_c/x86_64-windows-msvc/c/netioapi.cr
> +  NDIS_IF_MAX_STRING_SIZE = 256u16
fixed

2025-05-16 21:01 UTC, foxxx0 commented on src/lib_c/aarch64-android/c/net/if.cr
> +  IF_NAMESIZE = 16u8
fixed

2025-05-16 21:01 UTC, foxxx0 commented on spec/std/socket/address_spec.cr
> +    it { Socket::IPAddress.parse_v6_fields?("fe80:0:0:0:ffff:c0a8:5e4%lo").should eq UInt16.static_array(65152, 0, 0, 0, 65535, 49320, 1508, 0) }
fixed

2025-05-16 21:43 UTC, foxxx0 commented on src/socket/address.cr
> +      LibC.if_indextoname(@zone_id, buf)
It appears that did break some specs:
```
1) Socket::IPAddress #zone_id looks up loopback interface name by index

Failed to look up interface name for index 1 (ECHILD) (Socket::Error)
```
Since that spec passed before without issues, there is either some lingering `errno` set or I should be much more selective on which `errno` are actually an issue. So only look for `Errno::ENXIO` or would there be others I need to watch out for?

2025-05-18 09:01 UTC, foxxx0 commented on src/socket/address.cr
> +      String.new(buf.to_unsafe)
I have added the macro now, please let me know if you want this implemented differently.

2025-05-18 09:04 UTC, foxxx0 commented on src/socket/address.cr
> +      LibC.if_indextoname(@zone_id, buf)
After some more experimentation and research I've learned to only look at `Errno` if the `LibC` return value indicates an error. For `if_indextoname()` this means:
```
On success, if_indextoname() returns ifname; on error, NULL is returned and errno is set appropriately. 
```
I've adjusted to code according to check if `LibC.if_indextoname()` returns a `NULL` pointer and only then look at `Errno`.
Additionally I've added a spec to trigger the `ENXIO` condition and it expects a `Socket::Error` to be raised.

2025-05-18 09:05 UTC, foxxx0 commented on spec/std/socket/address_spec.cr
> +      Socket::IPAddress.new("fe80::4545", 0).link_local_interface.should be_nil
I've added a spec to cover this scenario now.

2025-05-19 08:17 UTC, ysbaddaden commented
> I don't really grasp why unsigned integers in the stdlib should be avoided.

To avoid mixed signed/unsigned types in user code, especially since we allow transparent cross type math, and the first type in the expression determines the result... it quickly becomes hard to know the actual type of something —I personally try to use Int32 as much as possible, and use a special type when it's really needed.

This is the same for the port: it's usually an UInt16 in the system, but we use `Int` for ease of use. The UInt32 constraint would require to manually cast a variable to u32, when the compiler can do it automatically.

2025-05-19 08:20 UTC, ysbaddaden commented on src/socket/address.cr
> +      {% if flag?(:wasi) %}
**Polish:** you can test whether the method exists:

```suggestion
      {% unless LibC.has_method?(:if_nametoindex) %}
```

2025-05-19 08:23 UTC, ysbaddaden approved these changes

2025-05-19 08:29 UTC, straight-shoota commented
For cases like this zone id, a proper type-safe solution would probably be to introduce a dedicated type `ZoneID` which is incompatible with any integer type and forces you to convert it explicitly if you want to do any math with it.
We don't do that in other places in stdlib yet, so we shouldn't introduce it here. But might be worth considering as a future enhancement.

2025-05-19 11:01 UTC, foxxx0 commented on src/socket/address.cr
> +      String.new(buf.to_unsafe)
adjusted to
```crystal
{% unless LibC.has_method?(:if_nametoindex) %}
```

2025-05-19 11:54 UTC, straight-shoota commented
I'm not happy about the `Int` restrictions. IMO they're wrong. We should not change the existing type restrictions, but we should avoid introducing new ones.

`Int` includes all integer types, so it's allowed to call the method with `Int64::MAX`, for example. But it's clear that such a value would never fit. With an `Int` restriction, there's no compile-time validation. It'll only raise at runtime.
With an `Int32` restrictions, however, we still get implicit autocasting for all compatible types. But if the source type is bigger than `Int32`, we need to cast explicitly at the call site. This can help identify issues at compile time.

IMO input and output types should always be identical, so `Int32` both for the parameter type and the return type.

2025-05-19 13:54 UTC, foxxx0 commented
That is definitely a good catch. I've adjusted `zone_id` to `Int32` everywhere now.

2025-05-19 14:01 UTC, HertzDevil commented
[Windows CI](https://github.com/crystal-lang/crystal/actions/runs/15111219217/job/42481003901) is failing, because [Win32 presumably does not set `errno` at all](https://learn.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-if_nametoindex), and the `ENOENT` you're seeing probably came from another C runtime function call:

> If the **if_nametoindex** function fails and returns zero, it is not possible to determine an error code.

2025-05-19 14:35 UTC, foxxx0 commented
> [Windows CI](https://github.com/crystal-lang/crystal/actions/runs/15111219217/job/42481003901) is failing, because [Win32 presumably does not set `errno` at all](https://learn.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-if_nametoindex), and the `ENOENT` you're seeing probably came from another C runtime function call:
> 
> > If the **if_nametoindex** function fails and returns zero, it is not possible to determine an error code.

Unfortunately I can't seem to find any useful `errno` documentation for windows w.r.t. `if_indextoname()` / `if_nametoindex()`.
Errors from `if_nametoindex()` are already handled regardless of errno via checking `zone_id.positive?`.
I have now adjusted the error handling for `if_indextoname()`, since a `NULL` pointer always indicates an error, regardless of what `errno` may or may not be present. For platforms with `errno` support, which include the following to my knowledge:
 - linux
 - bsd
 - darwin
 - solaris
the `Errno.value` is inspected and appended to the exception message unless it is `Errno::NONE`.
The corresponding spec is adjusted accordingly.

2025-05-19 14:49 UTC, tboedecker-godaddy commented on src/socket/address.cr
> +        {% if flag?(:linux) || flag?(:bsd) || flag?(:darwin) || flag?(:solaris) %}
I seriously doubt that the other `wasi` / `wasm` variants have `errno`.

2025-05-19 14:59 UTC, straight-shoota commented on src/socket/address.cr
> +        {% if flag?(:linux) || flag?(:bsd) || flag?(:darwin) || flag?(:solaris) %}
We don't eve have bindings for `if_indextoname` on wasi, so that's really irrelevant here until we actually implement that. And then it should be the outliers mentioned explicitly, not the common cases.

2025-05-19 15:48 UTC, foxxx0 commented on src/socket/address.cr
> +        {% if flag?(:linux) || flag?(:bsd) || flag?(:darwin) || flag?(:solaris) %}
fine by me as well, adjusted.

2025-05-19 16:07 UTC, straight-shoota approved these changes

2025-05-19 18:05 UTC, foxxx0 commented on src/socket/address.cr
> +        raise Error.new("Failed to look up interface name for index #{@zone_id}#{errno_msg}")
that looks a bit cleaner indeed, implemented.

2025-05-20 14:32 UTC, foxxx0 commented
Are we good to merge now?

2025-05-20 15:21 UTC, ysbaddaden approved these changes

2025-05-20 15:33 UTC, straight-shoota approved these changes

2025-05-22 08:21 UTC, merged

2025-05-22 10:19 UTC, straight-shoota commented on src/socket/address.cr
> +    # using `#link_local_interface` on the `IPAddress` object.
Improving documentation sounds good for a follow-up 👌

I'm not sure about name vs. id. `#to_s` is supposed to be a user-friendly format, so that would be an argument to show the name instead of the id there...

2025-05-22 20:40 UTC, foxxx0 commented on src/socket/address.cr
> +    # using `#link_local_interface` on the `IPAddress` object.
Modifying the `#to_s` output would be a breaking change. There are likely lots of things/applications/libs that occasionally convert an IPv4/IPv6 address to a string and handing them off to whatever. Each of these implementations would then potentially need adjusting if there was suddenly a `%<zone_id>` suffix as part of the string.

I do think a separate `#to_s_rfc4007`? method might be useful to get that exact format. With an optional boolean to chose between numerical `zone_id` and `link_local_interface`.

2025-05-22 22:10 UTC, Sija commented on src/socket/address.cr
> +    # using `#link_local_interface` on the `IPAddress` object.
> I do think a separate `#to_s_rfc4007`? method might be useful to get that exact format. With an optional boolean to chose between numerical `zone_id` and `link_local_interface`.

Sounds like a great idea. I'd suggest using a dedicated named argument in `to_s` instead.

2025-05-23 10:24 UTC, RX14 commented on src/socket/address.cr
> +    # using `#link_local_interface` on the `IPAddress` object.
Correct me if I'm wrong, but the current state of this PR looks like `to_s` is modified instead of inspect.

2025-05-23 10:44 UTC, straight-shoota commented on src/socket/address.cr
> +    # using `#link_local_interface` on the `IPAddress` object.
Yes, this PR adds the zone ID to the output of both, `#to_s` and `#inspect` (the latter delegates to the former).
We missed adding a spec for that to make it explicit.
Considering https://github.com/crystal-lang/crystal/pull/15263/files#r2103365809 this might have been an unintended change and we should revert that.

> I'd prefer for inspect to always include the zone.

Agreed. The information should be there. But should it be ID or name?
Maybe ID because it's sufficient and more succinct?

2025-05-23 13:31 UTC, foxxx0 commented on src/socket/address.cr
> +    # using `#link_local_interface` on the `IPAddress` object.
After taking another look, the `#to_s` always returned the address accompanied by the port. If one wanted to obtain just the address, there is an `#address` method, which hasn't been modified by this PR, i.e. it doesn't include any `%<zone_id>`, neither numerical nor string.

It is indeed true, that we've now implicitly changed the `#to_s` behavior with a potentially breaking formatting change. This was definitely an oversight as there is also no spec for it.

I can follow up with another PR for adding an optional bool to `#to_s` that controls whether or not to include the `zone_id`.

Should we default to always include it or omit it in `#to_s` to keep previous behavior and only always include it in `#inspect`?

2025-05-23 15:30 UTC, foxxx0 commented on src/socket/address.cr
> +    # using `#link_local_interface` on the `IPAddress` object.
One more thing worth noting:
Since `zone_id` can only ever be set (i.e. `.positive?`) on `link-local` ipv6 addresses, the format change doesn't really affect anything.
If at all, it actually might fix certain implementations since `link-local` ipv6 addresses might not even work properly *without* the `zone_id`.

But I still thing we can make improvements in both the comments/docs, default behavior and obviously also add some specs for that.