refactor: use top_level_semantic in doc spec instead of semantic
crystal-lang/crystal pull request #9352
Opened 2020-05-25 12:07 UTC by MakeNowJust

This PR adds `top_level_semantic` utility methods for compiler spec, and uses this in doc spec. `crystal docs` command [uses `top_level_semantic`](https://github.com/crystal-lang/crystal/blob/b3ebb1cde9c08eb15d3401775b7d5b8811335d7f/src/compiler/crystal/command/docs.cr#L139), so the spec follows it.

2023-07-10 13:23 UTC, nobodywasishere reviewed
Everything looks good to me - though I don't have write access so I cannot merge this PR. Does this generate the exact same docs as just 'semantic'? And how kuch faster is this?

2023-07-10 14:54 UTC, straight-shoota commented
I'm not sure about the `wants_doc = true` default because its different from anywhere else.
I suppose it makes kind of sense when it's only used for doc generator specs.
However then I'd maybe consider extracing a specific helper method for that and maybe returns a `Doc::Generator` instance?

2023-07-10 15:42 UTC, nobodywasishere reviewed
I don't think this should've been removed. It's why CI is broken

2023-07-10 15:44 UTC, nobodywasishere requested changes

2023-09-20 17:49 UTC, straight-shoota approved these changes
Specs are green now 🚀

2023-12-12 11:57 UTC, HertzDevil commented on spec/spec_helper.cr
> +def top_level_semantic(code : String, wants_doc = true, inject_primitives = false)
I don't think `wants_doc` should have a different default value from `::semantic`, as it is entirely possible we want to use `top_level_semantic` in other places

2023-12-12 11:58 UTC, HertzDevil commented on spec/spec_helper.cr
> +  node : ASTNode
Does this really need to be a distinct type from `SemanticResult`?

2023-12-12 12:41 UTC, HertzDevil approved these changes

2023-12-13 13:32 UTC, merged