Complex: moving math methods to Math
crystal-lang/crystal pull request #9739
Opened 2020-09-10 15:48 UTC by cristian-lsdb

Moving `Complex#exp`. `Complex#log`, `Complex#log2`, `Complex#log10` and `Complex#sqrt` to Math.

2020-09-10 17:56 UTC, bcardiff requested changes
Please leave the specs in complex_spec.cr, they can be in a `describe Math` block, but they should live in that file.

Also, run `$ crystal tool format` to make CI (and humans) happy.

2020-09-11 19:40 UTC, cristian-lsdb commented
Thank you for your feedback. You are right it’s cleaner to keep all spec for complex in the same file. I have updated the PR with the required changes.

2020-09-11 20:10 UTC, bcardiff approved these changes

2020-10-30 18:32 UTC, bcardiff commented
@cristian-lsdb can you rebase this on master so the CI is happy. We are still missing one more 👍  review before merging, but since de CI is (wrongly) complaining that might mislead other reviewers.

2020-11-01 23:22 UTC, straight-shoota approved these changes

2020-11-06 19:15 UTC, merged